const PI=3.14159265;
const NW=33.4;  // molecules/nm³ in liquid water

// TRACK-STRUCTURE SCALES — both NEUTRAL (1.0). The track-structure physics
// has no tuning scalars; these are kept as neutral hooks for provenance and
// sensitivity experiments. Do not set either off 1.0 without a Geant4 source
// citation (the RESEARCH_STANDARDS no-fudge rule).
// - SIGMA_EXC_SCALE multiplies the excitation σ total (XC). History: 0.5
//   (v0.3.0) → 0.39 (v0.6.1) — a flat factor approximating Born by scaling the
//   Emfietzoglou table. v0.7.0 (E29) regenerated cross_sections.wgsl from the
//   REAL Born excitation data (sigma_excitation_e_born.dat; XC and XEF are now
//   Born), matching G4EmDNAPhysics_option2 — the list BOTH Geant4 oracles
//   register. The Emf/Born ratio is energy-dependent (~2.5× at keV, ~10× at
//   ~10 eV), so no flat scale could match it; loading Born directly closed the
//   sub-keV CSDA deficit (100 eV 0.78→0.96×). The scale is now a no-op: 1.0.
// - RECOMB_BOOST scaled the Onsager P_recomb in every e-h recombination check.
//   It had NO Geant4 physical basis (the H₂O⁺ refutation: Geant4's recomb is
//   one-shot single-sample, not time-integrated) and E10r showed it was not
//   load-bearing. Set to 1.0 (neutral) at v0.5.0; the flip passed all three
//   gates — cascade ions 0.677→0.766× [E7d], chemistry parameter-free at
//   +1.4 pp RMS [E10r], SSB ratio in band [E13d]. The full cascade (v0.6.0)
//   and Born excitation (v0.7.0) then improved every axis further.
const SIGMA_EXC_SCALE:f32=1.0;
const RECOMB_BOOST:f32=1.0;

// Cross sections (XE, XI, XC, XL, XSF*, XAE, XAC, XWE, XWS*) plus
// their log-space indexing constants (LOG_XE0, INV_LOG_XE_STEP, ...)
// are prepended to this shader at load time by fetching
// /cross_sections.wgsl (generated by tools/convert_g4data.py).
// DO NOT inline them here — edit the converter instead.

// Shell binding energies (eV) — G4DNAWaterIonisationStructure
const SB=array<f32,5>(10.79,13.39,16.05,32.30,539.0);
// Oxygen K-shell (1a1, 539 eV) Auger electron energy (KLL, ~503 eV). The K-hole
// de-excites overwhelmingly by Auger (fluorescence yield <1%); Geant4-DNA emits
// it via G4UAtomicDeexcitation. Without it the 439-806 eV secondary band is ~43%
// short (E8). 539 - 503 = ~36 eV of L-shell rearrangement stays as a local deposit.
const E_AUGER:f32=503.0;
// Excitation energies (eV) — G4DNAEmfietzoglouWaterExcitationStructure
const EX=array<f32,5>(8.22,10.00,11.24,12.61,13.77);

fn xs_all(E:f32)->vec3<f32>{
  if(E<=XE[0]){return vec3<f32>(0.0,0.0,XL[0]);}
  if(E>=XE[XN-1u]){return vec3<f32>(XI[XN-1u],XC[XN-1u]*SIGMA_EXC_SCALE,XL[XN-1u]);}
  let t=(log(E)-LOG_XE0)*INV_LOG_XE_STEP;
  let i=u32(clamp(floor(t),0.0,f32(XN-2u)));
  let f=t-f32(i);
  let j=i+1u;
  return vec3<f32>(
    max(0.0,XI[i]+(XI[j]-XI[i])*f),
    max(0.0,XC[i]+(XC[j]-XC[i])*f)*SIGMA_EXC_SCALE,
    max(0.0,XL[i]+(XL[j]-XL[i])*f)
  );
}

fn xs_shell_fracs(E:f32)->array<f32,5>{
  if(E<=XE[0]){return array<f32,5>(XSF0[0],XSF1[0],XSF2[0],XSF3[0],XSF4[0]);}
  if(E>=XE[XN-1u]){return array<f32,5>(XSF0[XN-1u],XSF1[XN-1u],XSF2[XN-1u],XSF3[XN-1u],XSF4[XN-1u]);}
  let t=(log(E)-LOG_XE0)*INV_LOG_XE_STEP;
  let i=u32(clamp(floor(t),0.0,f32(XN-2u)));
  let f=t-f32(i);
  let j=i+1u;
  return array<f32,5>(
    max(0.0,XSF0[i]+(XSF0[j]-XSF0[i])*f),
    max(0.0,XSF1[i]+(XSF1[j]-XSF1[i])*f),
    max(0.0,XSF2[i]+(XSF2[j]-XSF2[i])*f),
    max(0.0,XSF3[i]+(XSF3[j]-XSF3[i])*f),
    max(0.0,XSF4[i]+(XSF4[j]-XSF4[i])*f)
  );
}

fn xs_exc_fracs(E:f32)->array<f32,5>{
  // XEF holds the 5 excitation-level fractions (from sigma_excitation_e_born.dat).
  // Historical guard: the OLD Emfietzoglou table degenerated above ~8.6 keV
  // (each level read 1.0 from the converter → row-sum ≈ 5), so we clamp the
  // index to the last good bin (85). The current Born table is clean — every
  // high-index row sums to exactly 1.0 (verified 2026-06-23) — so this clamp is
  // now a DORMANT safety net. Side effect: it freezes branching at bin 85 for
  // E > ~10.2 keV (XE[85]); that range is outside the validated 100 eV–10 keV
  // envelope, so it is a no-op for every headline result. Removing the clamp to
  // use the valid Born high-E fractions is a physics change pending revalidation.
  if(E<=XE[0]){return array<f32,5>(XEF0[0],XEF1[0],XEF2[0],XEF3[0],XEF4[0]);}
  if(E>=XE[XN-1u]){return array<f32,5>(XEF0[85],XEF1[85],XEF2[85],XEF3[85],XEF4[85]);}
  let t=(log(E)-LOG_XE0)*INV_LOG_XE_STEP;
  var i=u32(clamp(floor(t),0.0,f32(XN-2u)));
  // Clamp index to bin 85 — the dormant Emfietzoglou-era guard; a no-op for the
  // clean Born table (every high-index row sums to 1.0). See the note above.
  if(i>85u){i=85u;}
  let f=select(t-f32(i),0.0,i==85u);
  let j=min(i+1u,85u);
  let v0=max(0.0,XEF0[i]+(XEF0[j]-XEF0[i])*f);
  let v1=max(0.0,XEF1[i]+(XEF1[j]-XEF1[i])*f);
  let v2=max(0.0,XEF2[i]+(XEF2[j]-XEF2[i])*f);
  let v3=max(0.0,XEF3[i]+(XEF3[j]-XEF3[i])*f);
  let v4=max(0.0,XEF4[i]+(XEF4[j]-XEF4[i])*f);
  return array<f32,5>(v0,v1,v2,v3,v4);
}

fn xs_el_cos(E:f32,r:f32)->f32{
  let rr=clamp(r,0.0,1.0);
  let jf=rr*f32(N_AC-1u);
  let jlo=u32(floor(jf));
  let jhi=min(jlo+1u,N_AC-1u);
  let fj=jf-f32(jlo);
  let tE=(log(max(E,XAE[0]))-LOG_XAE0)*INV_LOG_XAE_STEP;
  let iE=u32(clamp(floor(tE),0.0,f32(N_AE-2u)));
  let fE=clamp(tE-f32(iE),0.0,1.0);
  let base0=iE*N_AC;
  let base1=(iE+1u)*N_AC;
  let c00=XAC[base0+jlo];let c01=XAC[base0+jhi];
  let c10=XAC[base1+jlo];let c11=XAC[base1+jhi];
  let cE0=c00+(c01-c00)*fj;
  let cE1=c10+(c11-c10)*fj;
  return clamp(cE0+(cE1-cE0)*fE,-1.0,1.0);
}

// Sample total energy transfer from Born differential ionization CDF.
// Uses paired CDF/E_transfer arrays with binary search (same algorithm as Geant4).
// Inputs: E_primary (eV), shell (0..4), r uniform in [0,1).
// Returns E_transfer (eV) = binding + secondary_KE.
fn sample_W_sec(E:f32,shell:u32,r:f32)->f32{
  // Find nearest primary energy in XWE via binary search
  // (XWE is NOT log-spaced — raw Born grid, linear below 30 eV)
  var lo:u32=0u;var hi:u32=N_WE-1u;
  while(hi-lo>1u){let mid=(lo+hi)/2u;if(XWE[mid]<=E){lo=mid;}else{hi=mid;}}
  let iE=select(lo,hi,abs(XWE[hi]-E)<abs(XWE[lo]-E)); // nearest
  let base=iE*N_WR;
  return bsearch_cdf(shell,base,r);
}
// Binary search in CDF array, return interpolated E_transfer.
fn bsearch_cdf(shell:u32,base:u32,r:f32)->f32{
  // Linear scan (N_WR=100, cheap; binary search saves ~50 iterations but
  // WGSL has no recursion and loop overhead is similar for N=100)
  var jlo:u32=0u;
  for(var j=0u;j<N_WR-1u;j++){
    let c=get_cdf(shell,base+j);
    if(c<=r){jlo=j;}else{break;}
  }
  let jhi=min(jlo+1u,N_WR-1u);
  let c0=get_cdf(shell,base+jlo);
  let c1=get_cdf(shell,base+jhi);
  let e0=get_etransfer(shell,base+jlo);
  let e1=get_etransfer(shell,base+jhi);
  if(c1<=c0){return e0;}
  let f=clamp((r-c0)/(c1-c0),0.0,1.0);
  // Linear interpolation (matches Geant4 G4DNACrossSectionDataSet log-log
  // on the raw data; our paired CDF breakpoints are already on the raw grid
  // so linear between breakpoints = same as np.interp on raw data)
  return e0+(e1-e0)*f;
}
fn get_cdf(shell:u32,idx:u32)->f32{
  if(shell==0u){return XWC0[idx];}
  if(shell==1u){return XWC1[idx];}
  if(shell==2u){return XWC2[idx];}
  if(shell==3u){return XWC3[idx];}
  return XWC4[idx];
}
fn get_etransfer(shell:u32,idx:u32)->f32{
  if(shell==0u){return XWT0[idx];}
  if(shell==1u){return XWT1[idx];}
  if(shell==2u){return XWT2[idx];}
  if(shell==3u){return XWT3[idx];}
  return XWT4[idx];
}

// Total Sanche vibrational cross section. Valid in 2-100 eV, zero outside.
// XVE is NOT log-spaced so we do a linear scan (N_VIB ~ 38, cheap).
fn xs_vib_total(E:f32)->f32{
  if(E<2.0||E>100.0){return 0.0;}
  for(var i=0u;i<N_VIB-1u;i++){
    if(E>=XVE[i]&&E<XVE[i+1u]){
      let f=(E-XVE[i])/(XVE[i+1u]-XVE[i]);
      return max(0.0,XVS[i]+(XVS[i+1u]-XVS[i])*f);
    }
  }
  return 0.0;
}

// Sample a vibrational mode (0..8) at energy E given uniform r in [0,1).
// Modes with threshold > E are disallowed.
fn sample_vib_mode(E:f32,r:f32)->u32{
  // Find bin i
  var bin:u32=0u;
  for(var i=0u;i<N_VIB-1u;i++){
    if(E>=XVE[i]&&E<XVE[i+1u]){bin=i;break;}
  }
  // Use the lower bin's fractions (no cross-bin interp needed — fine resolution)
  let base=bin*9u;
  // Build cumulative weighted CDF, respecting per-mode threshold (mode cannot fire if VIB_LEV[k] > E)
  var cumsum:f32=0.0;
  var cs:array<f32,9>;
  for(var k=0u;k<9u;k++){
    let frac=select(XVMF[base+k],0.0,VIB_LEV[k]>E);
    cumsum=cumsum+frac;
    cs[k]=cumsum;
  }
  if(cumsum<=0.0){return 0u;}
  let thr=r*cumsum;
  for(var k=0u;k<9u;k++){
    if(thr<cs[k]){return k;}
  }
  return 8u;
}

// Melton dissociative electron attachment: e⁻ + H₂O → OH⁻ + H (4–13 eV)
// Data: G4EMLOW sigma_attachment_e_melton.dat, converted 1e-18 cm² → nm²
const DEA_N = 14u;
const DEA_E = array<f32,14>(0.0, 4.2, 4.3, 5.8, 6.0, 6.2, 6.4, 7.0, 7.5, 7.7, 8.4, 10.2, 11.2, 12.3);
const DEA_S = array<f32,14>(0.0, 0.0, 0.0, 2.5e-5, 2.8e-4, 6.0e-4, 6.7e-4, 3.7e-4, 1.09e-4, 7.0e-5, 1.4e-4, 2.0e-5, 6.0e-5, 0.0);
fn xs_dea(E:f32)->f32{
  if(E<4.0||E>13.0){return 0.0;}
  for(var i=0u;i<DEA_N-1u;i++){
    if(E>=DEA_E[i]&&E<DEA_E[i+1u]){
      let f=(E-DEA_E[i])/(DEA_E[i+1u]-DEA_E[i]);
      return max(0.0,DEA_S[i]+(DEA_S[i+1u]-DEA_S[i])*f);
    }
  }
  return 0.0;
}

fn rl(x:u32,k:u32)->u32{return(x<<k)|(x>>(32u-k));}
fn rn(s:ptr<function,vec4u>)->u32{let r=rl((*s).x+(*s).w,7u)+(*s).x;let t=(*s).y<<9u;(*s).z^=(*s).x;(*s).w^=(*s).y;(*s).y^=(*s).z;(*s).x^=(*s).w;(*s).z^=t;(*s).w=rl((*s).w,11u);return r;}
fn rf(s:ptr<function,vec4u>)->f32{return f32(rn(s)>>1u)/2147483647.0;}

// --- Shared pure helpers (R2 dedup, WGSL_REFACTOR_PARITY_PROTOCOL.md) ---
// Moved verbatim from primary.wgsl (were duplicated in primary, secondary,
// and — for deposit() — proton). Uniform-agnostic by construction: deposit
// takes (box, vc) as explicit params, meesungnoen_sigma takes only k, and
// neither draws RNG. Each bundle declares its own `dose` storage binding,
// which these resolve against at compile time per bundle.

// Meesungnoen2002: electron thermalization penetration → 1D Gaussian sigma (nm)
// Polynomial fit to mean radial distance, converted via sigma = r_mean * sqrt(pi/8)
fn meesungnoen_sigma(k:f32)->f32{
  if(k<=0.1){return 0.0;}
  var r=-4.06217193e-08;
  r=r*k+3.06848412e-06;r=r*k-9.93217814e-05;r=r*k+1.80172797e-03;
  r=r*k-2.01135480e-02;r=r*k+1.42939448e-01;r=r*k-6.48348714e-01;
  r=r*k+1.85227848e+00;r=r*k-3.36450378e+00;r=r*k+4.37785068e+00;
  r=r*k-4.20557339e+00;r=r*k+3.81679083e+00;r=r*k-2.34069784e-01;
  return max(r,0.0)*0.6267;
}

// Deposit energy (eV) at voxel containing world position (px,py,pz). Thread-safe.
// Dose is stored in fixed-point: 100 units = 1 eV.
fn deposit(px:f32,py:f32,pz:f32,dep_eV:f32,box:f32,vc:u32){
  if(dep_eV<=0.0){return;}
  let vs=2.0*box/f32(vc);
  let ix=i32(floor((px+box)/vs));
  let iy=i32(floor((py+box)/vs));
  let iz=i32(floor((pz+box)/vs));
  let n=i32(vc);
  if(ix<0||ix>=n||iy<0||iy>=n||iz<0||iz>=n){return;}
  let vi=u32((iz*n+iy)*n+ix);
  atomicAdd(&dose[vi],u32(dep_eV*100.0));
}

// Electron-hole recombination → H2Ovib dissociation (R2 dedup,
// WGSL_REFACTOR_PARITY_PROTOCOL.md). Shared verbatim by all 7 call sites
// across the primary + secondary shaders: primary ionization (sub-cutoff +
// tracked-secondary estimate), primary B1A1 + L2-4 autoionization, and the
// three mirror sites in the secondary shader.
//
// Draws r_recomb, then (only if fired) r_vd from s — the same order as
// every inlined copy this replaces. Returns true when recombination fired
// (the caller runs its site-specific no-recomb path otherwise).
//
// Params: r_sep = H2O+→eaq separation in nm (callers clamp to > 0);
// (mx,my,mz) = mother-displaced emission site; pid = primary lineage tag
// (pid or parent_pid); dep_val = per-event deposited energy (e_dep_ion for
// ionization sites, dep for excitation sites); (dx,dy,dz) = true deposit
// site written to rad_dep (always the interaction point); max_rad = the
// caller buffer bound (p.max_rad vs sp.max_rad); emit_o selects the
// oxygen-marker variant — ionization sites (and secondary excitation)
// emit the O atom (code 4, 3 entries) while primary excitation emits 2 H
// only (2 entries). Behavior preserved exactly per site, NOT unified.
fn emit_recomb(r_sep: f32, mx: f32, my: f32, mz: f32, pid: f32,
               dep_val: f32, dx: f32, dy: f32, dz: f32,
               max_rad: u32, emit_o: bool,
               s: ptr<function,vec4u>) -> bool {
  let p_recomb = min(1.0, RECOMB_BOOST * (1.0 - exp(-0.711 / max(r_sep, 1e-6))));
  let r_recomb = rf(s);
  if (r_recomb >= p_recomb) { return false; }
  // Electron-hole recombination: H2O+ + eaq → H2Ovib → dissociation
  let r_vd = rf(s);
  if (r_vd < 0.1365) {
    // 13.65% → 2OH + H2
    atomicAdd(&counters[0], 2u);
    atomicAdd(&counters[5], 1u); // H2 counter
    let ri = atomicAdd(&counters[7], 3u);
    if (ri + 2u < max_rad) {
      rad_buf[ri]       = vec4<f32>(mx, my, mz, 0.0 + pid);
      rad_e[ri] = dep_val; rad_dep[ri] = vec4<f32>(dx, dy, dz, 0.0);
      rad_buf[ri + 1u] = vec4<f32>(mx, my, mz, 0.0 + pid);
      rad_e[ri + 1u] = dep_val; rad_dep[ri + 1u] = vec4<f32>(dx, dy, dz, 0.0);
      rad_buf[ri + 2u] = vec4<f32>(mx, my, mz, 7.0 + pid);
      rad_e[ri + 2u] = dep_val; rad_dep[ri + 2u] = vec4<f32>(dx, dy, dz, 0.0);
    }
  } else if (r_vd < 0.494) {
    // 35.75% → OH + H
    atomicAdd(&counters[0], 1u);
    atomicAdd(&counters[2], 1u);
    let ri = atomicAdd(&counters[7], 2u);
    if (ri + 1u < max_rad) {
      rad_buf[ri]       = vec4<f32>(mx, my, mz, 0.0 + pid);
      rad_e[ri] = dep_val; rad_dep[ri] = vec4<f32>(dx, dy, dz, 0.0);
      rad_buf[ri + 1u] = vec4<f32>(mx, my, mz, 2.0 + pid);
      rad_e[ri + 1u] = dep_val; rad_dep[ri + 1u] = vec4<f32>(dx, dy, dz, 0.0);
    }
  } else if (r_vd < 0.650) {
    // 15.6% → 2H + O (O = code 4 — the oxygen-network seed, option3 chemistry)
    atomicAdd(&counters[2], 2u);
    if (emit_o) {
      let ri = atomicAdd(&counters[7], 3u);
      if (ri + 2u < max_rad) {
        rad_buf[ri]       = vec4<f32>(mx, my, mz, 2.0 + pid);
        rad_e[ri] = dep_val; rad_dep[ri] = vec4<f32>(dx, dy, dz, 0.0);
        rad_buf[ri + 1u] = vec4<f32>(mx, my, mz, 2.0 + pid);
        rad_e[ri + 1u] = dep_val; rad_dep[ri + 1u] = vec4<f32>(dx, dy, dz, 0.0);
        rad_buf[ri + 2u] = vec4<f32>(mx, my, mz, 4.0 + pid);
        rad_e[ri + 2u] = dep_val; rad_dep[ri + 2u] = vec4<f32>(dx, dy, dz, 0.0);
      }
    } else {
      // Primary excitation emits 2 H only (O not tracked there)
      let ri = atomicAdd(&counters[7], 2u);
      if (ri + 1u < max_rad) {
        rad_buf[ri]       = vec4<f32>(mx, my, mz, 2.0 + pid);
        rad_e[ri] = dep_val; rad_dep[ri] = vec4<f32>(dx, dy, dz, 0.0);
        rad_buf[ri + 1u] = vec4<f32>(mx, my, mz, 2.0 + pid);
        rad_e[ri + 1u] = dep_val; rad_dep[ri + 1u] = vec4<f32>(dx, dy, dz, 0.0);
      }
    }
  }
  // else: 35% relaxation — no products
  return true;
}
