#!/usr/bin/env python3
"""Convert Geant4-DNA proton cross-section data -> public/proton_cross_sections.wgsl.

Generates the tabulated total cross sections the proton shader needs:
  - Rudd ionisation (< 500 keV): sigma_ionisation_p_rudd.dat (5 shells, scaleFactor 1 m^2)
  - Born ionisation (> 500 keV): sigma_ionisation_p_born.dat (5 shells, G4EMLOW scale)
  - Born excitation (> 500 keV): sigma_excitation_p_born.dat (5 levels, G4EMLOW scale)
Miller-Green excitation (< 500 keV) and the Rudd secondary-electron differential are
ANALYTICAL — implemented directly in helpers.wgsl, no tables needed (matches
G4DNAMillerGreenExcitationModel / G4DNARuddIonisationModel).

Reference: G4EmDNAPhysics_option2 ConstructDNAProtonPhysics — both Geant4 oracles
(dnaphysics, chem6) register option2 (E29).
"""
import sys, numpy as np
from pathlib import Path

DATA = Path("data/g4emlow/dna")
N = 100                       # subsample points (log-spaced)
E_MIN, E_MAX = 1e2, 1e8       # eV — proton tracking range (100 eV - 100 MeV)
RUDD_SCALE = 1e18             # m^2 -> nm^2 (Rudd scaleFactor = 1 m^2)
BORN_SCALE = 2.993e-5         # G4EMLOW raw -> nm^2 (same as electron Born)

def load(fname, scale):
    p = DATA / fname
    if not p.exists():
        print(f"MISSING {p}"); sys.exit(1)
    raw = np.loadtxt(p)
    E = raw[:, 0].astype(np.float64)
    sig = raw[:, 1:].astype(np.float64) * scale   # (rows, 5)
    return E, sig

# ONE shared grid for all proton cross sections, so the shader's single
# log-index lookup (PLOG0/PINV_LOG_STEP) is valid for PRI/PBI/PBX alike.
GRID = np.exp(np.linspace(np.log(E_MIN), np.log(E_MAX), N))

def onto_grid(E, tot):
    m = tot > 0
    if m.sum() < 2:
        return np.zeros(N)
    out = np.exp(np.interp(np.log(GRID), np.log(E[m]), np.log(tot[m]),
                           left=np.log(1e-30), right=np.log(1e-30)))
    # zero outside the source data's support (no extrapolation)
    out[(GRID < E[m][0]) | (GRID > E[m][-1])] = 0.0
    return out

def logsub(E, tot, n):
    return GRID, onto_grid(E, tot)

def wgsl_arr(name, a, fmt="{:.6e}"):
    return f"const {name}=array<f32,{len(a)}>(" + ",".join(fmt.format(float(x)) for x in a) + ");"

def main():
    print("--- Proton Rudd ionisation ---")
    eR, sR = load("sigma_ionisation_p_rudd.dat", RUDD_SCALE)
    totR = sR.sum(axis=1)
    print(f"  {len(eR)} rows, peak total {totR.max():.4e} nm^2 at {eR[totR.argmax()]:.0f} eV")
    grid, rudd_tot = logsub(eR, totR, N)
    # per-shell fractions on the grid
    rudd_fr = []
    for s in range(5):
        m = sR[:, s] > 0
        fr = np.exp(np.interp(np.log(grid), np.log(eR[m]), np.log(sR[m, s]),
                              left=np.log(1e-30), right=np.log(1e-30))) if m.sum() >= 2 else np.zeros(N)
        rudd_fr.append(np.where(rudd_tot > 0, fr / np.maximum(rudd_tot, 1e-30), 0))

    print("--- Proton Born ionisation ---")
    eBI, sBI = load("sigma_ionisation_p_born.dat", BORN_SCALE)
    _, born_ion = logsub(eBI, sBI.sum(axis=1), N)

    print("--- Proton Born excitation ---")
    eBE, sBE = load("sigma_excitation_p_born.dat", BORN_SCALE)
    _, born_exc = logsub(eBE, sBE.sum(axis=1), N)

    lg0 = float(np.log(grid[0])); lgs = float((np.log(grid[-1]) - np.log(grid[0])) / (N - 1))
    out = [
        "// === PROTON CROSS SECTIONS (Geant4-DNA option2) ===",
        "// Generated by tools/convert_proton_data.py from G4EMLOW 8.8.",
        "// Rudd ionisation (<500 keV) + Born (>500 keV); Miller-Green excitation",
        "// and the Rudd secondary differential are analytical (helpers.wgsl).",
        f"const PN={N}u;",
        wgsl_arr("PE", grid, "{:.4f}"),
        wgsl_arr("PRI", rudd_tot),       # Rudd total ionisation
        wgsl_arr("PBI", born_ion),       # Born total ionisation
        wgsl_arr("PBX", born_exc),       # Born total excitation
        f"const PLOG0={lg0:.8f};",
        f"const PINV_LOG_STEP={1.0/lgs:.8f};",
    ]
    for s in range(5):
        out.append(wgsl_arr(f"PRF{s}", rudd_fr[s]))   # Rudd per-shell fractions
    Path("public/proton_cross_sections.wgsl").write_text("\n".join(out) + "\n")
    print(f"\nWrote public/proton_cross_sections.wgsl ({N} points, grid {grid[0]:.0f}-{grid[-1]:.3e} eV)")
    # sanity peaks
    print(f"  Rudd ion peak {rudd_tot.max():.4e} nm^2 @ {grid[rudd_tot.argmax()]:.0f} eV")
    print(f"  Born ion @ 1 MeV: {born_ion[np.argmin(np.abs(grid-1e6))]:.4e} nm^2")

if __name__ == "__main__":
    main()
